### ISSUE TITLE
Problem with Dispatcher's System declaration order

### ISSUE THREAD

**Issue by VoxWave** [slide-rs/shred#104]
```Rust
let mut dispatcher = DispatcherBuilder::new()
    .with(PhysicsSystem, "physics_system", &["player_control_system"])    
    .with(CollisionSystem, "collision_system", &["physics_system"])    
    .with(PlayerControlSystem::new(recv), "player_control_system", &[])    
    .build();
```
This panics because the `PhysicsSystem` depends on the `PlayerControlSystem` before it is added to the dispatcher. Shouldn't the order in which the systems are added not matter since the dispatcher is built using the builder pattern?

**Comment by omni-viral** [comment]
Current behavior protects from cycles.
If someone would fix this bug s?he should double-check that dispatcher still disallow cycles.

**Comment by torkleyy** [comment]
This is simply a limitation of the current `Dispatcher`. I'm planning to pick up [`system-graph`](https://github.com/slide-rs/system-graph) to solve this issue, but the `Dispatcher` will probably just stay this way.
