### ISSUE TITLE
Add `System::dispose`

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/shred#119]
Requested by @Frizi.

`System::dispose` would be called by `Dispatcher::dispose` and can be used to clean up externally allocated resources.

## Unresolved

* Signature: `fn dispose(&self, world: &World)` / `fn dispose(&self, world: &mut World)` / `fn dispose(&mut self, world: &World)` / `fn dispose(&mut self, world: &mut World)`
* Is it mandatory to call it? How to make sure it gets called?

**Comment by LucioFranco** [comment]
@torkleyy curious what is the difference between this and drop?

**Comment by torkleyy** [comment]
It has access to `World`, which is required for access to `rendy::Factory` in this case.

**Comment by LucioFranco** [comment]
@torkleyy that makes sense, I would imagine in that case a `fn dispose(&mut self, world: &mut World)` might make sense here.

**Comment by torkleyy** [comment]
Yeah, I think that makes sense.

**Comment by torkleyy** [comment]
Now, how do we make sure it gets called?

One option would be to set a flag when it gets called, and check it is set in `Dispatcher::drop`.
