### ISSUE TITLE
Improve support for generics by #[derive(SystemData)]

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/shred#35]
* Allow `where`-clause
* Allow HRTBs
* Check it compiles by adding an example

**Comment by torkleyy** [comment]
@pedrohjordao Please comment here whether or not it doesn't work for you.

**Comment by pedrohjordao** [comment]
I'll be looking into it tomorrow

**Comment by torkleyy** [comment]
Don't worry, figured it out myself. It's going to be fixed in a few minutes.
