### ISSUE TITLE
Thread-local-resources

### ISSUE THREAD

**Issue by Binero** [slide-rs/shred#45]
It would be nice to have thread-local-resources, as in, resources that do not implement Sync. 

It would be useful for systems that need access to things like `gfx::Device`, `gfx::Encoder` or `gfx::pso::buffer::ConstantBuffer`.

**Comment by torkleyy** [comment]
Indeed an interesting request, but I don't know how we would implement that, actually. Is there some wrapper which only allows access from one thread but is itself `Send` and `Sync`?

**Comment by torkleyy** [comment]
See https://github.com/slide-rs/shred/pull/51
