### ISSUE TITLE
Try to remove `Send` / `Sync` from `Resource`

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/shred#97]
It might be worth exploring a version of shred that doesn't force anybody using the `Dispatcher`, which forces thread-safety on all resources.

**Comment by omni-viral** [comment]
I wonder why dispatcher forces `Send + Sync`?
If only thread_local systems are added then it `Send + Sync` shouldn't be required

**Comment by torkleyy** [comment]
I don't think there's any useful solution to this; `!Send` are best stored in systems and synchronized with the data in the world, so e.g. processing can happen in parallel.

There's also no construct that allows fast, efficient and type-safe access to `!Send` resources.
